name: qmdb
description: "Flutter assignment for Q Agency"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: 14.6.0
  dio: ^5.7.0
  fpdart: ^1.1.1
  connectivity_plus: ^6.1.0
  alice: ^0.4.2
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  logger: 2.0.2+1
  hive: 2.2.3
  hive_flutter: 1.1.0
  hooks_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1


dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10




flutter:

  uses-material-design: true

  assets:
    - assets/icons/